#!/bin/bash

#  afs-checkattach - Evaluate any logged volume attach errors
#  Copyright (C) 2015  Alexander Boström, KTH
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e; set -o pipefail

export PATH=/usr/sbin:/sbin:"$PATH"

loggedattachids=$( { { fgrep 'volume' /usr/afs/logs/VolserLog || :; } | sed -nre 's,^.* Volser: GetVolInfo: Could not attach volume ([0-9]+) .*$,\1,p; s,^.* DumpVnode: volume ([0-9]+) .*$,\1,p;'; { fgrep 'needs to be salvaged' /usr/afs/logs/FileLog || :; } | sed -nre 's,^.* VAttachVolume: volume /vicep([^/]+)/V0*([0-9]+)\.vol needs to be salvaged.*$,\2,p;'; } | sort -u) || loggedattachids=""

if [[ -n "$loggedattachids" ]]; then
    attachfailids=""
    for volid in $loggedattachids; do
        if env LC_ALL=en_US.UTF-8 vos exa -id "$volid" -localauth -noresolve -encrypt 2>/dev/null | fgrep 'Could not attach volume' >/dev/null; then
            attachfailids="$attachfailids $volid"
        fi
    done

    if [[ -n "$attachfailids" ]]; then
        volnames=""
        for volid in $attachfailids; do
            volname=$(env LC_ALL=en_US.UTF-8 vos listvldb -name "$volid" -localauth -noresolve -quiet -nosort -encrypt|egrep '^[^ ]') || volname=""
	    if [[ -n "$volname" ]]; then
	        volnames="$volnames $volname"
	    else
	        volnames="$volnames id=$volid"
	    fi
        done
        echo "Could not attach some volumes: $volnames"
        exit 2
    fi
fi

echo "Currently no volume attach errors."

exit 0
