#!/bin/bash

#  afs-checkvols - Make sure all volumes of a server are fully available
#  Copyright (C) 2015  Alexander Boström, KTH
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e; set -o pipefail

declare -a failedvols
declare -i exitcode=0

for part in $(vos listpart -localauth -server 127.0.0.1 -noresolve | sed -nre 's,^ +/vicep(.*) *$,\1,p;'); do
    vos listvol -localauth -server 127.0.0.1 -part $part -noresolve | 
    sed -nre '/^[^ ]+\.(readonly|backup)/d; s,^([^ ]+) +[0-9].*$,\1,p;' |
    sort -u |
    while read volname; do
        echo "$volname $part"
        if vos dump -id "$volname" >/dev/null 2>/dev/null -server 127.0.0.1 -part $part -localauth -noresolve; then
            continue
        else
            exitcode=1
            failedvols+=("$volname")
        fi
    done
done

if (( exitcode > 0 )); then
    echo "Failed volumes, in need of bos salvage:" "${failedvols[@]}"
    exit $exitcode
fi

echo "All volumes ok"
